sudo: required

env:
- DOCKER_COMPOSE_VERSION: 1.4.2

services:
- docker

before_install:
- rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- mv docker-compose /usr/local/bin
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io

install:
- docker-compose -p gctortravis -f docker-compose-local-auth.yml build

script:
- AUTH_MODULE_URL="$AUTH_MODULE_URL" docker-compose -p gctortravis -f docker-compose-local-auth.yml run webtests

notifications:
  email: false
  slack:
    secure: JOZIqZ8s4vFEtmgMYSy6TlVqIXiyjDWYhdkxIRg4SlXwcD/akuXM6Zn8S9J5kbmLcA7swZ5Z7Pu+v7Zhkq9MlJd09Dj2ROYBg9fL8biLhfte9WUK9lG/uAoNmOLeAApzhUhLRnXJR6lY7hPfUCUW5iWVWWvBbVKz6aw5MORaoasO097IHkmUZhVZdnajfZ5NFEc4EIyrZ/tn3ovR+eYg8zqdtUOsA+xY7+568bcg5gBqeY/zjTBVIrgoZ87j4/OdEQ/35v57iTQSc28O/uGBLg8c3NBxp+pvhueMWMkPyqzm4QacU0x3N3uOE2/9MZdicyW9+J99xe/19O/xrxkjrBWPDASdYIhCfhY9X/TzQmZ3xnIDR7KzW2cE5H5hrhxFnXc6hZ2hALkmA7QyV7mBnBGH09LHdDpB0yczdz+Xp42UQSCIag71dJRxDpO2FV+FRfQdrWAbFt5IVN0tll6OqX7DyI8gvo9YmjCSt5ZTWPm8YcW/GALwAD/oNt2mZSReMaRPjpzous3yLoF0++/MGJ0w4w80P3bMgoOLJX137vm4jXh0e1ZPDBTcmNK8XKZCdfljq0FPkp2ny80I+cdf6JjX3oNmcTpdrSVB4RYjosVjH/jl+pj1hBK+p4qf63BSmWLbc+uBT6k3eKPEE1g7RqmVvefPwfki8J1TO2chM2Q=
