language: node_js
node_js:
  - '4'
python:
  - "2.7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
  - pip install biopython
script:
  - npm run lint
  - npm run test
cache:
  directories:
    - node_modules
