genome-designer:
  image: quay.io/autodesk_bionano/genome-designer-qa
  links:
    - redis
  ports:
    - "80:3000"
    - "6379:6379"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker 
    - /usr/lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02 


redis:
  image: redis:3
  command: redis-server
