command: python3 translate.py inputs/genbank outputs/block outputs/sequence
inputs:
    - id: genbank
      type: string

outputs:
    - id: block
      type: string
    - id: sequence
      type: string

